name: dart_slack_bot
description: "Slack bot client for Dart."
version: 0.0.1
homepage: https://example.com

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  build_runner: ^2.4.11
  envied: ^1.0.0
  http: ^1.2.2

dev_dependencies:
  envied_generator: ^1.0.0
  lints: ^4.0.0
  test: ^1.25.8

